[package]
name = "number"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = { version = "0.4.0", default-features = false, features = ["scalar_field"] } 
ark-ff = "0.4.2"
num-bigint = "0.4.3"
num-traits = "0.2.15"
