[package]
name = "powdr"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
codespan-reporting = "0.11.1"
json = "0.12.4"
lalrpop-util = {version = "0.19.8", features = ["lexer"]}
mktemp = "0.5.0"
regex = "1"

[build-dependencies]
lalrpop = "0.19.8"
