[package]
name = "powdr"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
clap = { version = "^4.1", features = ["derive"] }
codespan-reporting = "^0.11"
itertools = "^0.10"
json = "^0.12"
lalrpop-util = {version = "^0.19", features = ["lexer"]}
mktemp = "0.5.0"
num-bigint = "^0.4"

[build-dependencies]
lalrpop = "^0.19"
