[workspace]

members = [
    "number",
    "parser",
    "powdr_cli",
    "executor",
    "riscv",
    "parser_util",
    "pil_analyzer",
    "compiler",
    "pilgen",
    "halo2",
]

[patch."https://github.com/privacy-scaling-explorations/halo2.git"]
halo2_proofs = { git = "https://github.com/appliedzkp/halo2.git", rev = "d3746109d7d38be53afc8ddae8fdfaf1f02ad1d7" }

[patch.crates-io]
halo2_proofs = { git = "https://github.com/appliedzkp/halo2.git", rev = "d3746109d7d38be53afc8ddae8fdfaf1f02ad1d7" }
