[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[features]
halo2 = ["dep:halo2"]

[dependencies]
halo2 = { path = "../halo2", optional = true }
estark = { path = "../estark" }
number = { path = "../number" }
strum = { version = "0.24.1", features = ["derive"] }
ast = { version = "0.1.0", path = "../ast" }
#log = "0.4.17"
thiserror = "1.0.43"

[dev-dependencies]
#test-log = "0.2.12"
