[package]
name = "pil_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
json = "^0.12"
mktemp = "0.5.0"
number = { path = "../number" }
parser_util = { path = "../parser_util" }
parser = { path = "../parser" }
pilgen = { path = "../pilgen" }
itertools = "^0.10"
ast = { version = "0.1.0", path = "../ast" }
