[package]
name = "pilgen"
version = "0.1.0"
edition = "2021"

[dependencies]
number = { path = "../number" }
parser_util = { path = "../parser_util" }
parser = { path = "../parser" }
rustc-demangle = "0.1.23"
