[package]
name = "powdr-plonky3"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
powdr-ast = { version = "0.1.0-alpha.1", path = "../ast" }
powdr-number = { version = "0.1.0-alpha.1", path = "../number" }
rand = "0.8.5"
powdr-analysis = { path = "../analysis" }
powdr-executor = { path = "../executor" }
serde_json = "1.0.116"

p3-air = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }
p3-matrix = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }
p3-field = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }
p3-uni-stark = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }
p3-commit = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af", features = ["test-utils"] }
p3-poseidon2 = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }
p3-poseidon = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }
p3-fri = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }
p3-mds = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }
p3-merkle-tree = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }
p3-goldilocks = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }
p3-symmetric = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }
p3-dft = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }
p3-challenger = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }
p3-util = { git = "https://github.com/Plonky3/Plonky3.git", rev = "7e4f7af" }

[dev-dependencies]
powdr-pipeline = { path = "../pipeline" }
