[package]
name = "parser"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
lalrpop-util = {version = "^0.19", features = ["lexer"]}
number = { path = "../number" }
parser_util = { path = "../parser_util" }
# This is only here to work around https://github.com/lalrpop/lalrpop/issues/750
# It should be removed once that workaround is no longer needed.
regex-syntax = { version = "0.6", default_features = false, features = ["unicode"] }

[build-dependencies]
lalrpop = "^0.19"