[package]
name = "parser"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
lalrpop-util = {version = "^0.19", features = ["lexer"]}
number = { path = "../number" }
parser_util = { path = "../parser_util" }

[build-dependencies]
lalrpop = "^0.19"