[package]
name = "powdr"
description = "Main powdr crate, re-exporting the key APIs"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
powdr-backend = { path = "../backend" }
powdr-executor = { path = "../executor" }
powdr-number = { path = "../number" }
powdr-pipeline = { path = "../pipeline" }
powdr-riscv = { path = "../riscv" }
powdr-riscv-executor = { path = "../riscv-executor" }
